config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#home'

  devise_for :users

  post 'dashboard/search'

  resources :tasks do
    collection do
      get :my_tasks
    end
  end

  resources :comments, only: [:create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :task
  belongs_to :user
end

app/models/file_path.rb
class FilePath < ApplicationRecord
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :file_paths
  has_many :comments
  accepts_nested_attributes_for :file_paths, reject_if: :all_blank, allow_destroy: true
  CATEGORIES = %w(Configuration Code ILV)

  def created_at_date
    created_at.strftime("%d %b, %y")
  end

  def created_by?(current_user)
    user_id.eql?(current_user.id) rescue false
  end

  def self.with_category(category)
    if category.blank? || !self::CATEGORIES.include?(category)
      all
    else
      where(category: category)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tasks
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_task

  def create
    @comment = current_user.comments.create(comment_params)
  end

  private
    def comment_params
      params.require(:comment).permit(:content, :task_id)
    end

    def set_task
      @task = Task.find(comment_params[:task_id])
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  protect_from_forgery
  skip_before_action :authenticate_user!

  def home
    @tasks = Task.all
  end

  def search

    # binding.pry
    @tasks = Task.with_category(params['category']).where('title LIKE ?', '%'+params['query']+'%')
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :must_authenticate_user, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_task, only: [:edit, :update, :destroy]
  before_action :find_task, only: [:show]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = current_user.tasks.new
  end

  def edit
  end

  def my_tasks
    @tasks = current_user.tasks
  end

  def create
    @task = current_user.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to my_tasks_tasks_path, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def find_task
      @task = Task.find(params[:id])
    end

    def set_task
      @task = current_user.tasks.find(params[:id]) rescue unauthenticate_try
    end

    def task_params
      params.require(:task).permit(:category, :title, :description, file_paths_attributes: [:id, :name, :description, :_destroy])
    end

    def must_authenticate_user
      redirect_to root_path, notice: 'You must login first to perform this action' unless user_signed_in?
    end

    def unauthenticate_try
      redirect_to my_tasks_tasks_path, notice: 'You can only update tasks added or created by you!'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
    case level
    when :notice then "alert alert-info"
    when :success then "alert alert-success"
    when :error then "alert alert-danger"
    when :alert then "alert alert-warning"
    when :recaptcha_error then "alert alert-danger"
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/comments/_comment.html.erb
<div class="comment" id="comment-<%= comment.id %>">
  <%= comment.content %>
  <div class="commenter-detail">
    <small>
      by <b><%= comment.user.email %></b>
      on <b><%= comment.created_at.strftime("%d %b, %y") %></b>
      at <b><%= comment.created_at.strftime("%H:%M %p") %></b>
    </small>
  </div>
</div>

app/views/comments/_comments.html.erb
<div class="comment-form" id="comment-form-for-task-<%= task.id %>">
  <%= form_for(task.comments.new, remote: true) do |f| %>
    <%= f.text_field :content, class: 'form-control', placeholder: 'Enter your suggestion...' %>
    <br>
    <%= f.hidden_field :task_id %>
    <%= f.submit 'Submit', class: 'btn btn-primary form-control' %>
  <% end %>
</div>

<div class="comments" id="comments-for-task-<%= task.id %>">
  <% task.comments.order(:created_at).reverse.each do |comment| %>
    <%= render partial: 'comments/comment', locals: {comment: comment} if comment.persisted? %>
  <% end %>
</div>

app/views/comments/create.js.erb
$("#comments-for-task-<%= @task.id%>").prepend("<%= escape_javascript(render partial: 'comments/comment', locals: {comment: @comment}) %>")
$("#comment-form-for-task-<%= @task.id %>").find('#comment_content').val("");

app/views/common/_flash_msg.html.erb
<% flash.each do |name, msg| %>
  <% unless msg.blank? %>
    <div class="<%= flash_class(name.to_sym) %> fade in">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <%= content_tag :p, flash[name.to_sym] %>
    </div>
  <% end %>
<% end %>

app/views/common/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Tasks</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'New Task', new_task_path %></li>
          <li><%= link_to 'My Task', my_tasks_tasks_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <% if user_signed_in? %>
            <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to 'Login', new_user_session_path %>
          <% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/dashboard/home.html.erb
<div class="cool-md-12">
  <%= select_tag :category, options_for_select(Task::CATEGORIES), class: "form-control category-for", prompt: 'All' %>
  <br>
  <input type="text" name="search" class="form-control" id="search-query" placeholder="Search here....">
</div>
<br><br>

<div class="col-md-12 all-tasks">
  <%= render partial: 'tasks/tasks' %>
</div>

<script>
  $(document).on('keyup', '#search-query',function(){
    var query = $(this).val();
    var category = $('.category-for').val();
    if (query.length >= 3) {
      $.ajax({
        type: "POST",
        url: "<%= dashboard_search_path %>",
        data: { category: category, query: query }
      });
    }
  });
</script>

app/views/dashboard/search.js.erb
$('.all-tasks').html("<%= escape_javascript(render partial: 'tasks/tasks') %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TasksManagement</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <%= render partial: 'common/header' %>
    <%= render partial: 'common/flash_msg' %>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_file_path_fields.html.erb
<div class='nested-fields file-fields'>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", placeholder: '' %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", placeholder: '' %>
  </div>
  <%= link_to_remove_association "remove file path", f %>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category %>
    <%= form.select :category, options_for_select(Task::CATEGORIES, 'all'), {}, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :task_title, class: "form-control", placeholder: '' %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :task_description, class: "form-control", placeholder: '' %>
  </div>

  <h3>Files</h3>
  <div id='file_paths'>
    <%= form.fields_for :file_paths do |file| %>
      <%= render 'file_path_fields', :f => file %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association 'add file path', form, :file_paths, class: 'btn btn-primary' %>
    </div>
  </div>
  <br><br>
  <div class="actions">
    <%= form.submit 'Create Task', class: 'btn btn-primary form-control' %>
  </div>
<% end %>

app/views/tasks/_tasks.html.erb
<div class="row">
  <div class="col-md-3">
    Total: <%= @tasks.try(:count) %>
  </div>
  <div class="col-md-3">
    Configuration: <%= @tasks.group_by(&:category)["Configuration"].try(:count) || 0 %>
  </div>
  <div class="col-md-3">
    Code: <%= @tasks.group_by(&:category)["Code"].try(:count) || 0 %>
  </div>
  <div class="col-md-3">
    ILV: <%= @tasks.group_by(&:category)["ILV"].try(:count) || 0 %>
  </div>
</div>

<% @tasks.each do |task| %>
  <a href="<%= task_path(task) %>" class="task-link">
    <div class="task">
      <h4><%= task.title %></small></h4>
      <p><%= task.description.truncate(100) %></p>
      <small><b>by:</b> <%= task.user.email %> on <%= task.created_at_date %></small>
      <% if task.created_by?(current_user)%>
        <small class="actions pull-right">
          <%= link_to 'Edit', edit_task_path(task) %> |
          <%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %>
        </small>
      <% end %>
    </div>
  </a>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class="col-md-12 all-tasks">
  <%= render partial: 'tasks/tasks' %>
</div>

app/views/tasks/my_tasks.html.erb
<div class="col-md-12 all-tasks">
  <%= render partial: 'tasks/tasks' %>
</div>

app/views/tasks/new.html.erb
<h3 class="text-center">New Task</h3>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<p>
  <strong>Category:</strong>
  <%= @task.category %>
</p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<h5><b>Files:</b></h5>
<ul>
  <% @task.file_paths.each do |file_path| %>
    <li><%= file_path.name %></li>
  <% end if @task.file_paths.present? %>
</ul>
<br>
<h4>Comments or Suggestions:</h4>

<%= render partial: 'comments/comments', locals: { task: @task } %>

<% if @task.created_by?(current_user) %>
  <%= link_to 'Edit', edit_task_path(@task) %> |
<% end %>

<%= link_to '<- Back', tasks_path %>